```yaml
name: accident-dashboard-env
channels:
  - defaults
dependencies:
  - python=3.10
  - pandas=1.5.3
  - numpy=1.23.5
  - plotly=5.13.1
  - dash=2.11.1
  - dash-bootstrap-components=1.4.1
  - scikit-learn=1.2.2
  - xgboost=1.7.5
  - imbalanced-learn
  - openpyxl=3.1.2
  - pip
  - pip:
      - git-lfs
